#! /usr/bin/env python
# -*- coding: utf-8 -*-

mch_yun = {     str('東'):"uwng",		
		str('冬'):"owng",
		str('鍾'):"jowng",
		str('江'):"aewng",
		str('支'):"je",
		str('脂'):"ij",
		str('之'):"i",
		str('微'):"j+j", # was miscoded before
		str('魚'):"jo",
		str('虞'):"ju",
		str('模'):"u",
		str('齊'):"ej",
		str('佳'):"ea+",
		str('皆'):"eaj",
		str('灰'):"*oj", # hekou
		str('咍'):"oj",
		str('真'):"jin",
		str('諄'):"win",
		str('臻'):"in",
		str('文'):"jun",
		str('欣'):"j+n",
		str('元'):"j*on", # hekou (???)
		str('魂'):"*on", #hekou
		str('痕'):"on",
		str('寒'):"an",
		str('桓'):"wan",
		str('刪'):"aen",
		str('山'):"ean",
		str('先'):"en",
		str('仙'):"jen", # maybe this should be simply stated as en????
		str('蕭'):"ew",
		str('宵'):"jew",
		str('肴'):"aew",
		str('豪'):"aw",
		str('歌'):"a",
		str('戈'):"wa",
		str('麻'):"ae",
		str('陽'):"jang",
		str('唐'):"ang",
		str('庚'):"aeng",
		str('耕'):"eang",
		str('清'):"jeng",
		str('青'):"eng",
		str('蒸'):"ing",
		str('登'):"ong",
		str('尤'):"juw",
		str('侯'):"uw",
		str('幽'):"iw",
		str('侵'):"im",
		str('談'):"am",
		str('覃'):"om",
		str('鹽'):"jem",
		str('添'):"em",
		str('咸'):"eam",
		str('銜'):"aem",
		str('嚴'):"jaem",
		str('凡'):"jom",
		str('董'):"uwng",
		str('腫'):"jowng",
		str('講'):"aewng",
		str('紙'):"je",
		str('旨'):"ij",
		str('止'):"i",
		str('尾'):"j+j", # was miscoded before
		str('語'):"jo",
		str('麌'):"ju",
		str('姥'):"u",
		str('薺'):"ej",
		str('蟹'):"ea+",
		str('駭'):"eaj",
		str('賄'):"*oj", # guess this is a hekou
		str('海'):"oj",
		str('軫'):"jin",
		str('准'):"win",
		str('吻'):"jun",
		str('隱'):"j+n",
		str('阮'):"j*on",
		str('混'):"*on", # hekou
		str('很'):"on",
		str('旱'):"an",
		str('緩'):"wan", # hekou
		str('潸'):"aen",
		str('產'):"ean",
		str('銑'):"en",
		str('獮'):"jen",
		str('筱'):"ew",
		str('小'):"jew",
		str('巧'):"aew",
		str('晧'):"aw",
		str('哿'):"a",
		str('果'):"wa",
		str('馬'):"ae",
		str('養'):"jang",
		str('蕩'):"ang",
		str('梗'):"aeng",
		str('耿'):"eang",
		str('靜'):"jeng",
		str('迥'):"eng",
		str('拯'):"ing",
		str('等'):"ong",
		str('有'):"juw",
		str('厚'):"uw",
		str('黝'):"iw",
		str('寢'):"im",
		str('感'):"am",
		str('敢'):"om",
		str('琰'):"jem",
		str('忝'):"em",
		str('豏'):"eam",
		str('檻'):"aem",
		str('儼'):"jaem",
		str('梵'):"jom",
		str('送'):"uwng",
		str('宋'):"owng",
		str('用'):"jowng",
		str('絳'):"aewng",
		str('寘'):"je",
		str('至'):"ij", # chongniu-rime
		str('志'):"i",
		str('未'):"j+j", # this was apparently miscoded as jij before!!!
		str('御'):"jo",
		str('遇'):"ju",
		str('暮'):"u",
		str('霽'):"ej",
		str('祭'):"jej",
		str('泰'):"aj",
		str('卦'):"ea+",
		str('怪'):"eaj",
		str('夬'):"aej",
		str('隊'):"*oj", # this seems to be an original hekou rime in Baxter's notion!!!
		str('代'):"oj",
		str('廢'):"joj",
		str('震'):"jin",
		str('稕'):"win",
		str('問'):"jun",
		str('焮'):"j+n",
		str('愿'):"j*on", #hekou???
		str('慁'):"*on", #hekou
		str('恨'):"on",
		str('翰'):"an",
		str('換'):"wan",
		str('諫'):"aen",
		str('襉'):"ean",
		str('霰'):"en",
		str('線'):"jen",
		str('嘯'):"ew",
		str('笑'):"jew",
		str('效'):"aew",
		str('號'):"aw",
		str('個'):"a",
		str('過'):"wa",
		str('禡'):"ae",
		str('漾'):"jang",
		str('宕'):"ang",
		str('映'):"aeng",
		str('諍'):"eang",
		str('勁'):"jeng",
		str('徑'):"eng",
		str('證'):"ing",
		str('嶝'):"ong",
		str('宥'):"juw",
		str('候'):"uw",
		str('幼'):"iw",
		str('沁'):"im",
		str('勘'):"am",
		str('鬫'):"om",
		str('艷'):"jem",
		str('陷'):"eam",
		str('鑒'):"aem",
		str('釅'):"jaem",
		str('范'):"jom",
		str('屋'):"uwk",
		str('沃'):"owk",
		str('燭'):"jowk",
		str('覺'):"aewk",
		str('質'):"jit",
		str('術'):"wit",
		str('櫛'):"it",
		str('物'):"jut",
		str('迄'):"j+t",
		str('月'):"j*ot", # not a pure hekou!!!
		str('沒'):"*ot", # original hekou
		str('曷'):"at",
		str('末'):"wat",
		str('黠'):"eat",
		str('轄'):"aet",
		str('屑'):"et",
		str('薛'):"jet",
		str('藥'):"jak",
		str('鐸'):"ak",
		str('陌'):"aek",
		str('麥'):"eak",
		str('昔'):"jek", # jek should be maintained!!!
		str('錫'):"ek",
		str('職'):"ik",
		str('德'):"*ok",
		str('緝'):"ip",
		str('合'):"ap",
		str('盍'):"op",
		str('葉'):"jep",
		str('帖'):"ep",
		str('洽'):"eap",
		str('狎'):"aep",
		str('業'):"jaep",
		str('乏'):"jop",
		str('篠'):"ew",
		str('準'):"win",
		str('噳'):"ju",
		str('箇'):"a",
		str('獼'):'jen', # probably chongniu? jen
		str('願'):'on', # no w
		str('合'):'op', # no w
		str('皓'):'aw',
		str('煔'):'em', 
		str('節'):'it', # 
		str('豔'):'jem'} # probably chongniu iem

mch_diao = {    str("入"):'rusheng',
		str('平'):'pingsheng',
		str('上'):'shangsheng',
		str('去'):'qusheng'}

mch_sheng = {   str('幫'):"p",
		str('滂'):"ph",
		str('並'):"b",
		str('明'):"m",
		str('端'):"t",
		str('知'):"tr",
		str('透'):"th",
		str('徹'):"trh",
		str('定'):"d",
		str('澄'):"dr",
		str('泥'):"n",
		str('娘'):"nr",
		str('見'):"k",
		str('溪'):"kh",
		str('群'):"g",
		str('疑'):"ng",
		str('精'):"ts",
		str('莊'):"tsr",
		str('章'):"tsy",
		str('清'):"tsh",
		str('初'):"tsrh",
		str('昌'):"tsyh",
		str('從'):"dz",
		str('崇'):"dzr",
		str('禪'):"dzy",
		str('心'):"s",
		str('生'):"sr",
		str('書'):"sy",
		str('邪'):"z",
		str('俟'):"zr",
		str('船'):"zy",
		str('影'):"'",
		str('曉'):"x",
		str('匣'):"h",
		str('云'):"hj",
		str('以'):"y",
		str('來'):"l",
		str('日'):"ny",
		str('非'):"pj",
		str('敷'):"phj",
		str('奉'):"bj",
		str('微'):"mj", 
		str('襌'):"dzy"}

mch_hu = {      str('開'):'kaikou',
		str('合'):'hekou'}

mch_deng = {    str('一'):'yideng',
		str('二'):'erdeng',
		str('三'):'sandeng',
		str('四'):'sideng'}

mch2ipa = [
        ("tsrh","ʦʰ"),
        ("tsyh","ʨʰ"),
        ("tsy","ʨ"),
        ("dzy","ʥ"),
        ("trh","ʈʰ"),
        ("tsh","ʦʰ"),
        ("tsr","t͡ʂ"),
        ("dzr","d͡ʐ"),
        ("jw","y"),
        ("ae","æ"),
        ("ea","ɛ"),
        ("ph","pʰ"),
        ("th","tʰ"),
        ("tr","ʈ"),
        ("ts","ʦ"),
        ("dr","ɖ"),
        ("nr","ɳ"),
        ("dz","ʣ"),
        ("sr","ʂ"),
        ("zr","ʐ"),
        ("kh","kʰ"),
        ("ny","ȵ"),
        ("sy","ɕ"),
        ("zy","ʑ"),
        ("ng","ŋ"),
        ("d","d"),
        ("n","n"),
        ("s","s"),
        ("z","z"),
        ("y","j"),
        ("k","k"),
        ("g","g"),
        ("x","x"),
        ("h","ɣ"),
        ("+","ɨ"),
        ("'","ʔ"),
        ("p","p"),
        ("b","b"),
        ("m","m"),
        ("t","t"),
        ("X","²"),
        ("H","³"),
        ("P","¹"),
        ("R","⁴")
        ]
